import Sidebar from "@/components/dashboard/Sidebar";
import Topbar from "@/components/dashboard/Topbar";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <main
          className="
                flex
                flex-row
                justify-start
                items-start
                min-h-screen
                
                bg-primary-light
                rounded-lg
                
                
            "
        >
          <Sidebar />
          <div
            className="
                    flex
                    flex-col
                    
                    w-full

                    h-full
                    justify-center
                    items-center
                  
                   bg-primary-light
                    "
          >
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
